port = '5432'
max_connections = 500
log_line_prefix = '%t [%p]: [%l-1] user=%u,db=%d,client=%h %r (%x:%e)'
log_level = 'ERROR'
data_checksums = true

[superuser]
name = 'admin'
password = 'admin'

# options for hot standby
[replication]
name = 'replication'
password = 'replication'
synchronous = true
synchronous_standby_names = '*'

[wal-e]
enable = false
[wal-e.aws]
prefix = ''
access_key_id = ''
secret_access_key = ''
region = ''
