port = '5432'
max_connections = 100
log_line_prefix = "%m: "
log_level = 'ERROR'

[superuser]
name = 'admin'
password = 'admin'

# options for hot standby
[replication]
name = 'replication'
password = 'replication'
lag_health_threshold = 1048576

[wal-e]
enable = false
[wal-e.aws]
prefix = ''
access_key_id = ''
secret_access_key = ''
region = ''
