{{ #with cfg.wal-e.aws }}
wale_s3_prefix='s3://{{bucket}}/{{../../../svc.service}}-{{../../../svc.group}}'
aws_access_key_id='{{access_key_id}}'
aws_secret_access_key='{{secret_access_key}}'
aws_region='{{region}}'
{{/with}}

[pg]
data_dir='{{pkg.svc_data_path}}'
superuser_name='{{cfg.superuser.name}}'
superuser_password='{{cfg.superuser.password}}'
