#!/bin/bash

set -ex

cd "${GROUP_CONTEXT}"

fail_count=$(cat ./* | jq '[.group[]| select(.state | contains("Failure"))] | length')

if [[ $fail_count -gt 0 ]]; then
  echo "Failure: $fail_count failures in build graph."
  exit 1
else
  echo "Success: 0 failures in build group."
  echo ""
  echo "Generating pipline from build group"
  exec /habitat-plans-ci/ci/scripts/metapipe
fi