# The options for consul are available here
# https://www.consul.io/docs/agent/options.html

[server]
datacenter = "dc1"
loglevel = "INFO"
bootstrap_expect = 3
# switch this to false you want to start in DEVMODE
# https://www.consul.io/docs/guides/bootstrapping.html
mode = false

[ports]
# The DNS server, -1 to disable
dns = 8600
# The HTTP API, -1 to disable
http = 8500
# The HTTPS API, -1 to disable
https = -1
# The CLI RPC endpoint
rpc = 8400
# The Serf LAN port
serf_lan = 8301
# The Serf WAN port
serf_wan = 8302
# Server RPC address
server = 8300

[client]
# What interface to bind to (defaults to all)
interface = "0.0.0.0"

# If you would like the web gui on the agent
[ui]
include = true
