---
meta:
  delmo:
    machine_name: habitat-plans-pipeline-machine
  dockerhub:
    email: REDACTED
    username: REDACTED
    password: REDACTED
  habitat:
    origin_key: REDACTED
    auth_token: REDACTED
    origin: eeyun
  aws:
    docker-machine-bucket: docker-machine-bucket
    docker-machine-ami: ami-41e0b93b
    access_key_id: REDACTED
    secret_access_key: REDACTED
    region: us-east-1
  concourse:
    target: REDACTED
    team: main
    user: concourse
    password: changeme
  slack:
    webhook: REDACTED

groups:
- name: all-packages
  jobs: []
- name: images
  jobs: [build-habitat-plans-pipeline-image]
- name: docker-machine-setup
  jobs: [docker-machine-setup]

jobs:
- name: build-habitat-plans-pipeline-image
  public: true
  plan:
  - aggregate:
    - {get: habitat-plans-pipeline, trigger: true}
    - {get: habitat-release, trigger: true}
  - put: habitat-plans-pipeline-image
    params:
      build: habitat-plans-pipeline/ci/image
      tag: habitat-release/version
      tag_as_latest: true

- name: docker-machine-setup
  serial: true
  plan:
  - task: docker-machine-setup
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: { repository: eeyun/docker-machine-setup }
      params:
        MACHINE_NAME: (( grab meta.delmo.machine_name ))
        AWS_DEFAULT_REGION: (( grab meta.aws.region ))
        AWS_ACCESS_KEY_ID: (( grab meta.aws.access_key_id ))
        AWS_SECRET_ACCESS_KEY: (( grab meta.aws.secret_access_key ))
        AWS_BUCKET: (( grab meta.aws.docker-machine-bucket ))
      run:
        path: /setup-aws

resources:
- name: habitat-plans-pipeline
  type: git
  source:
    uri: https://github.com/eeyun/ci-hab-test.git
    paths: [ci/image/*]

- name: habitat-plans-ci
  type: git
  source:
    uri: https://github.com/eeyun/ci-hab-test.git
    paths: [ci/*]

- name: habitat-release
  type: github-release
  source:
    user:         habitat-sh
    repository:   habitat
    access_token: REDACTED

- name: habitat-plans-pipeline-image
  type: docker-image
  source:
    email: (( grab meta.dockerhub.email ))
    username: (( grab meta.dockerhub.username ))
    password: (( grab meta.dockerhub.password ))
    repository: eeyun/habitat-plans-pipeline

- name: notify
  type: slack-notification
  source:
    url: (( grab meta.slack.webhook ))

resource_types:
- name: hab-pkg
  type: docker-image
  source:
    repository: cfcommunity/habitat-resource

- name: bldr-job
  type: docker-image
  source:
    repository: eeyun/bldr-resource

- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource
