---
groups:
- name: mysql
  jobs:
  - (( append ))
  - validate-mysql
  - test-mysql
  - release-mysql
- name: all-packages
  jobs:
  - (( append ))
  - test-mysql
  - release-mysql

jobs:
- name: validate-mysql
  public: true
  plan:
  - (( inline ))
  - aggregate:
    - (( append ))
    - get: eeyun-mysql-bldr-group
      trigger: true
    - {get: habitat-plans-ci}
  - task: validate-mysql-group
    privileged: true
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: { repository: eeyun/habitat-plans-pipeline }
      inputs:
      - name: eeyun-mysql-bldr-group
      - name: habitat-plans-ci
      outputs:
      - name: result
      run:
        path: ./habitat-plans-ci/ci/scripts/validate-group
      params:
        GROUP_CONTEXT: eeyun-mysql-bldr-group
        HAB_ORIGIN: eeyun
        PLAN_NAME: mysql
        HAB_ORIGIN_KEY: (( grab meta.habitat.origin_key ))
- name: test-mysql
  public: false
  serial: true
  serial_groups: [delmo]
  plan:
  - aggregate:
    - get: eeyun-mysql-bldr-group
      trigger: true
      passed: [validate-mysql]
    - {get: mysql-tests}
  - task: test-mysql
    privileged: true
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: { repository: eeyun/hab-delmo }
      params:
        GROUP_CONTEXT: eeyun-mysql-bldr-group
        PKG_CONTEXT: mysql
        MACHINE_EXPORT_AWS_ACCESS_KEY_ID: (( grab meta.aws.access_key_id ))
        MACHINE_EXPORT_AWS_SECRET_ACCESS_KEY: (( grab meta.aws.secret_access_key ))
        MACHINE_EXPORT_AWS_REGION: (( grab meta.aws.region ))
        MACHINE_EXPORT_AWS_BUCKET: (( grab meta.aws.docker-machine-bucket ))
        MACHINE_NAME: (( grab meta.delmo.machine_name ))
        AWS_ACCESS_KEY: (( grab meta.aws.access_key_id ))
        AWS_SECRET_KEY: (( grab meta.aws.secret_access_key ))
        AWS_REGION: (( grab meta.aws.region ))
      inputs:
      - name: mysql-tests
      - name: eeyun-mysql-bldr-group
      outputs:
      - name: notify_message
      run:
        path: /entrypoint.sh
    ensure:
      put: notify
      params:
        username: Hab-CI
        icon_url: https://brand.chef.io/images/habitat/logos/logo-3.png
        text_file: notify_message/message
- name: release-mysql
  public: true
  plan:
  - (( inline ))
  - aggregate:
    - (( inline ))
    - get: eeyun-mysql-bldr-group
      passed: [test-mysql]
      trigger: true
    - {get: habitat-plans-ci}
  - task: release-mysql
    privileged: true
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: { repository: eeyun/habitat-plans-pipeline }
      params:
        GROUP_CONTEXT: eeyun-mysql-bldr-group
        PKG_CONTEXT: eeyun/mysql
      inputs:
      - name: eeyun-mysql-bldr-group
      - name: habitat-plans-ci
      outputs:
      - name: notify_message
      run:
        path: ./habitat-plans-ci/ci/scripts/release_notify
  - aggregate:
    - put: eeyun-mysql-bldr-group
      params:
        result: eeyun-mysql-bldr-group
      on_success:
        put: notify
        params:
          username: Hab-CI
          icon_url: https://brand.chef.io/images/habitat/logos/logo-3.png
          text_file: notify_message/success_message
      on_failure:
        put: notify
        params:
          username: Hab-CI
          icon_url: https://brand.chef.io/images/habitat/logos/logo-3.png
          text_file: notify_message/failure_message

resources:
- name: eeyun-mysql-bldr-group
  type: bldr-job
  source:
    origin: (( grab meta.habitat.origin ))
    name: mysql
    auth_token: (( grab meta.habitat.auth_token ))
- name: mysql-tests
  type: git
  source:
    uri: https://github.com/eeyun/ci-hab-test.git
    paths: [mysql/tests/*]
